# Generated by Django 4.0.2 on 2022-03-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsApp', '0002_remove_comments_id_remove_like_id_comments_commentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='commentID',
        ),
        migrations.RemoveField(
            model_name='like',
            name='likeID',
        ),
        migrations.AddField(
            model_name='comments',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
